name: restaurant

services:

  rabbit:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - restaurant-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: q1sh-9D8S1-dxkPZZJ07Q
    networks:
      - restaurant-net

  eureka-server:
    build:
      context: eureka-server
    image: restaurant/eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - restaurant-net

  api-gateway:
    build:
      context: api-gateway
    image: restaurant/api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - restaurant-net

  auth-server:
    build:
      context: .
      dockerfile: auth-server/Dockerfile
    image: restaurant/auth-server:1.0
    container_name: auth-server
    networks:
      - restaurant-net
    ports:
      - "8484:8484"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: restaurant/user-service:1.0
    container_name: user-service
    networks:
      - restaurant-net

  mesa-service:
    build:
      context: .
      dockerfile: mesa-service/Dockerfile
    image: restaurant/mesa-service:1.0
    container_name: mesa-service
    depends_on:
      - rabbit
    networks:
      - restaurant-net

  reserva-service:
    build:
      context: .
      dockerfile: reserva-service/Dockerfile
    image: restaurant/reserva-service:1.0
    container_name: reserva-service
    depends_on:
      - mesa-service
      - rabbit
    networks:
      - restaurant-net

  transporte-service:
    build:
      context: .
      dockerfile: transporte-service/Dockerfile
    image: restaurant/transporte-service:1.0
    container_name: transporte-service
    depends_on:
      - rabbit
    networks:
      - restaurant-net

##########################
# Crea Los volúmenes #
##########################
volumes:
  mysql-data:
    driver: local
  config-server-data:
    driver: local

##########################
# Crea red de los servicios #
##########################
networks:
  restaurant-net:
    external: true